print("")
print("Hello! Welcome to Game!")
print("")
print("Pls Login")
print("")
name = input("Username: ")
print("Your Character:")
print("")
print("")
print("")
print("        ")
print("     |-------| ")
print("->   | ^   ^ | ")
print("->   |_______| ")
print("")
print("")
input()
clear()
print("")
print("")
print("")
print("")
print("                                                                                              ")
print("                                                                                              ")
print("  |------|                                                                                     ")
print("  | ^  ^ |                                                                                      ")
print("  |______|                   /\                                                                         ")
print("_________________/\=========|==|_________________                                                  ")
